swagger: "2.0"
info:
  title: Loan Origination API
  description: API for managing loan origination process
  version: "1.0"

schemes:
  - https
basePath: /api

paths:
  /loans:
    post:
      summary: Create a new loan application
      description: Creates a new loan application record
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loanApplication
          in: body
          description: Loan application details
          required: true
          schema:
            $ref: "#/definitions/LoanApplication"
      responses:
        201:
          description: Loan application created successfully
          schema:
            $ref: "#/definitions/LoanApplication"
          examples:
            application/json:
              loanId: "12345"
              applicantName: John Doe
              loanAmount: 50000
              duration: 24
              interestRate: 6.5
        400:
          description: Invalid request
        500:
          description: Internal server error

  /loans/{loanId}:
    get:
      summary: Get loan application by ID
      description: Retrieves loan application details by ID
      produces:
        - application/json
      parameters:
        - name: loanId
          in: path
          description: ID of the loan application
          required: true
          type: string
      responses:
        200:
          description: Loan application details retrieved successfully
          schema:
            $ref: "#/definitions/LoanApplication"
          examples:
            application/json:
              loanId: "12345"
              applicantName: John Doe
              loanAmount: 50000
              duration: 24
              interestRate: 6.5
        404:
          description: Loan application not found
        500:
          description: Internal server error

definitions:
  LoanApplication:
    type: object
    properties:
      loanId:
        type: string
        readOnly: true
      applicantName:
        type: string
      loanAmount:
        type: number
      duration:
        type: integer
      interestRate:
        type: number
    required:
      - applicantName
      - loanAmount
      - duration
      - interestRate
